# FolderStyleEditorForWindows configuration

[Features]
PinDoubleClickThreshold = 500

[AppInfo]
  HelpIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/message-circle-question-mark.svg"
  GitHubIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/github.svg"
  StarIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/star.svg"

[HoverIcon]
  DefaultIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/file.svg"
  ErrorIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/ban.svg"

  [HoverIcon.FileTypes]
  Supported = ["exe", "dll", "ico"]
  SupportedToConvert = ["png", "jpg", "jpeg", "bmp", "svg"]

  [[HoverIcon.MainIcons]]
  Extensions = ["exe", "dll"]
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/app-window.svg"

  [[HoverIcon.MainIcons]]
  Extensions = ["ico"]
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/book-image.svg"

  [[HoverIcon.BadgeIcons]]
  Status = "Supported"
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/badge/check.svg"

  [[HoverIcon.BadgeIcons]]
  Status = "SupportedToConvert"
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/badge/archive-restore.svg"

  [[HoverIcon.BadgeIcons]]
  Status = "Error"
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/ban.svg"

[PinIcon]
  MainIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/pin.svg"
  PinnedIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/pin.svg"
  UnpinnedIcon = "avares://FolderStyleEditorForWindows/Resources/SVG/pin-off.svg"
  TestPngPath = "avares://FolderStyleEditorForWindows/Resources/PNG/test-pin.png"

  [[PinIcon.BadgeIcons]]
  State = "Ready"
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/badge/arrow-down-0-1.svg"

  [[PinIcon.BadgeIcons]]
  State = "Waiting"
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/badge/arrow-down-1-0.svg"

  [[PinIcon.BadgeIcons]]
  State = "Success"
  IconPath = "avares://FolderStyleEditorForWindows/Resources/SVG/badge/check.svg"

[Animations]
ToastAnimationDuration = 300

[Appearance]
SvgDefaultColor = "#ff606064"

[Debug]
EnableOverlay = false
ShowHoverIconBackgroundColor = true
HoverIconBgColor = "#DD4444"
ShowSvgTest = true
SvgTestPath = "avares://FolderStyleEditorForWindows/Resources/SVG/book-image.svg"
ShowPngTest = true
PngTestPath = "avares://FolderStyleEditorForWindows/Resources/PNG/test-pin.png"
SvgOpacity = 0.75
ShowHoverIconClone = true

[LanguageDefaults]
ChineseCultures = ["zh-CN", "zh-Hans", "zh-CHS", "zh-Hant", "zh-HK", "zh-TW"]
EnglishCultures = ["en-US", "en-GB", "en"]
DefaultCulture = "zh-CN"
